# ***Practical Questions:***

###1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [3]:
import numpy as np

array = np.random.randint(1, 101, size=(3, 3))

# Interchange rows and columns (transpose)
transposed_array = np.transpose(array)

array, transposed_array


(array([[34, 99, 92],
        [76, 79, 55],
        [49, 43, 29]]),
 array([[34, 76, 49],
        [99, 79, 43],
        [92, 55, 29]]))

###2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [4]:
import numpy as np

array_1d = np.arange(10)

# Reshape into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

array_1d, array_2x5, array_5x2


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]))

###3.  Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

In [5]:
# Create a 4x4 NumPy array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros around the array, making it a 6x6 array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

array_4x4, array_with_border


(array([[0.48828245, 0.55288837, 0.95054829, 0.60079645],
        [0.43210817, 0.197186  , 0.04867403, 0.3543865 ],
        [0.6674451 , 0.65696711, 0.24588355, 0.06331091],
        [0.3344905 , 0.73376232, 0.2080707 , 0.82957376]]),
 array([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.48828245, 0.55288837, 0.95054829, 0.60079645,
         0.        ],
        [0.        , 0.43210817, 0.197186  , 0.04867403, 0.3543865 ,
         0.        ],
        [0.        , 0.6674451 , 0.65696711, 0.24588355, 0.06331091,
         0.        ],
        [0.        , 0.3344905 , 0.73376232, 0.2080707 , 0.82957376,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ]]))

###4.  Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [7]:
import numpy as np

array_step = np.arange(10, 61, 5)

array_step

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

###5.  Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [8]:
string_array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
upper_case = np.char.upper(string_array)
lower_case = np.char.lower(string_array)
title_case = np.char.title(string_array)
capitalize_case = np.char.capitalize(string_array)

upper_case, lower_case, title_case, capitalize_case

(array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6'),
 array(['python', 'numpy', 'pandas'], dtype='<U6'),
 array(['Python', 'Numpy', 'Pandas'], dtype='<U6'),
 array(['Python', 'Numpy', 'Pandas'], dtype='<U6'))

###6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [10]:
words_array = np.array(['hello', 'world', 'numpy', 'python'])

spaced_words = np.char.join(' ', words_array)

spaced_words


array(['h e l l o', 'w o r l d', 'n u m p y', 'p y t h o n'], dtype='<U11')

###7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

In [11]:
import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

addition, subtraction, multiplication, division

(array([[ 8, 10, 12],
        [14, 16, 18]]),
 array([[-6, -6, -6],
        [-6, -6, -6]]),
 array([[ 7, 16, 27],
        [40, 55, 72]]),
 array([[0.14285714, 0.25      , 0.33333333],
        [0.4       , 0.45454545, 0.5       ]]))

###8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

In [12]:
identity_matrix = np.eye(5)

diagonal_elements = np.diag(identity_matrix)

identity_matrix, diagonal_elements


(array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]),
 array([1., 1., 1., 1., 1.]))

###9.  Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [13]:
from sympy import isprime

random_integers = np.random.randint(0, 1000, 100)


prime_numbers = [num for num in random_integers if isprime(num)]

random_integers, prime_numbers

(array([533, 179,  51, 347, 494,  70, 719, 692, 995,  78, 991, 727, 490,
        335,  74,   6, 495, 290, 160, 637, 270, 664, 525, 397, 750, 187,
        652,  96, 198, 283, 332, 310,  89, 716, 328, 908, 899, 969, 220,
        606, 786, 955, 905, 317, 553, 958,  32, 984, 474, 927, 491, 821,
        828, 543, 270, 940, 446, 526, 511, 470, 415, 977, 193, 106,   3,
        387, 538, 121, 886, 251, 929, 783,  27, 648, 430, 574,  48, 736,
        237, 498, 347, 126, 175, 949, 449, 565, 288, 675, 228, 248, 677,
        465, 735, 310, 217, 339, 725,  40, 960, 566]),
 [179,
  347,
  719,
  991,
  727,
  397,
  283,
  89,
  317,
  491,
  821,
  977,
  193,
  3,
  251,
  929,
  347,
  449,
  677])

###10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [14]:
daily_temperatures = np.random.randint(15, 35, 30)

weeks = daily_temperatures[:28].reshape(4, 7)

weekly_averages = weeks.mean(axis=1)

daily_temperatures, weekly_averages

(array([26, 19, 16, 28, 23, 32, 20, 30, 30, 26, 17, 17, 28, 23, 18, 29, 24,
        18, 15, 26, 29, 21, 32, 31, 22, 23, 20, 17, 17, 23]),
 array([23.42857143, 24.42857143, 22.71428571, 23.71428571]))